version: '3.8'
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - backend
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: boileruser
      POSTGRES_PASSWORD: boilerpass
      POSTGRES_DB: boilerdb
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
